-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- USERS TABLE INDEXES

-- Index on user ID (usually already indexed as PRIMARY KEY)
-- CREATE INDEX idx_users_id ON users(id); -- Optional if not PK

-- Index on email for faster lookups (e.g., login)
CREATE INDEX idx_users_email ON users(email);


-- BOOKINGS TABLE INDEXES

-- Index on user_id for filtering/joining bookings by user
CREATE INDEX idx_bookings_user_id ON bookings(user_id);

-- Index on property_id for filtering/joining bookings by property
CREATE INDEX idx_bookings_property_id ON bookings(property_id);

-- Index on start_date date for searching upcoming bookings
CREATE INDEX idx_bookings_start_date ON bookings(start_date);

-- Index on end_date date (optional, if used in filters)
CREATE INDEX idx_bookings_end_date ON bookings(end_date);


-- PROPERTIES TABLE INDEXES

-- Index on host_id to retrieve all properties by a host
CREATE INDEX idx_properties_host_id ON properties(host_id);


END;