-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- Drop old partitioned structure if it exists (for safety in re-runs)
DROP TABLE IF EXISTS bookings CASCADE;

-- Create partitioned table with primary key that includes partition key
CREATE TABLE bookings (
    id SERIAL,
    user_id INTEGER NOT NULL,
    property_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, start_date) 
) PARTITION BY RANGE (start_date);

-- Create partitions
CREATE TABLE bookings_2023_q1 PARTITION OF bookings
    FOR VALUES FROM ('2023-01-01') TO ('2023-04-01');

CREATE TABLE bookings_2023_q2 PARTITION OF bookings
    FOR VALUES FROM ('2023-04-01') TO ('2023-07-01');

CREATE TABLE bookings_2023_q3 PARTITION OF bookings
    FOR VALUES FROM ('2023-07-01') TO ('2023-10-01');

CREATE TABLE bookings_2023_q4 PARTITION OF bookings
    FOR VALUES FROM ('2023-10-01') TO ('2024-01-01');

-- Create indexes on each partition (optional but recommended)
CREATE INDEX idx_bookings_q1_user_id ON bookings_2023_q1(user_id);
CREATE INDEX idx_bookings_q2_user_id ON bookings_2023_q2(user_id);
CREATE INDEX idx_bookings_q3_user_id ON bookings_2023_q3(user_id);
CREATE INDEX idx_bookings_q4_user_id ON bookings_2023_q4(user_id);

-- Performance test query using EXPLAIN ANALYZE
EXPLAIN ANALYZE
SELECT * 
FROM bookings
WHERE start_date BETWEEN '2023-04-01' AND '2023-06-30';


END;