-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- 1. Query to find all properties where the average rating is greater than 4.0 using a subquery
SELECT 
    properties.id,
    properties.title,
    properties.location
FROM 
    properties
WHERE 
    (
        SELECT AVG(reviews.rating)
        FROM reviews
        WHERE reviews.property_id = properties.id
    ) > 4.0;



-- 2. Correlated subquery to find users who have made more than 3 bookings
   	SELECT 
    users.id,
    users.name,
    users.email
FROM 
    users
WHERE 
    (
        SELECT COUNT(*)
        FROM bookings
        WHERE bookings.user_id = users.id
    ) > 3;

END;